### ISSUE TITLE
Chinese translation

### ISSUE THREAD

**Issue by Phunk87** [0xProject/whitepaper#3]
If there's not an official Chinese translation, I would like to do the translation.
@abandeali1 @willwarren89

**Comment by sunhuachuang** [comment]
chinese translation is [here](https://github.com/exchange-prototype/mozi/wiki/0x-%E7%99%BD%E7%9A%AE%E4%B9%A6-(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87%E7%89%88)) ：）

**Comment by abandeali1** [comment]
@sunhuachuang this is awesome, thank you!

**Comment by Phunk87** [comment]
@sunhuachuang great!

**Comment by HeadHunterz88** [comment]
Haha
